const USER_TYPE_WORKER = "USER_TYPE_WORKER";
const USER_TYPE_EMPLOYER = "USER_TYPE_EMPLOYER";
const DEFAULT_LIMIT = 1;
const DEFAULT_BALANCE = "0.00";

module.exports = {
  USER_TYPE_WORKER,
  USER_TYPE_EMPLOYER,
  DEFAULT_LIMIT,
  DEFAULT_BALANCE
};
